### ISSUE TITLE
Handling arrays of arrays

### ISSUE THREAD

**Issue by radhsv** [mfatihercik/dsm#14]
Trying to write config to handle array of arrays. 
Input to be parsed looks like:
```
[
  {
    "columns": [
      "name1",
      "name2",
      "name3"
    ],
    "events": [
      [
        "value1_1",
        "value1_2",
        "value1_3"
      ],
      [
        "value2_1",
        "value2_2",
        "value2_3"
      ],
      [
        "value3_1",
        "value3_2",
        "value3_3"
      ]
    ]
  }
]
```

Config (in JSON):
```
{
  "version": 1.0,
  "result":{
    "type":"object",
    "path":"/",
    "function": "processStuff",
    "fields":{
      "columns": {
        "type": "array"
      },
      "events": {
        "type": "array"
      }
    }
  }
}
```

The result looks like:
{columns=[name1, name2, name3], events=[value1_1, value1_2, value1_3, null, value2_1, value2_2, value2_3, null, value3_1, value3_2, value3_3, null]}

Looking to get a result like:
columns=[name1, name2, name3], events [[value1_1, value1_2, value1_3], [value2_1, value2_2, value2_3], [value3_1, value3_2, value3_3]]}

Tried a few variations of config but wasn't able to get the result I was looking for. Can DSM handle this kind of input?

**Comment by mfatihercik** [comment]
Unfortunately array of array is not supported for json. Do you have any suggestion how can I define array of array in  file? İf we can find a way to define in config then it is easy to implement.

**Comment by radhsv** [comment]
Here are a few ideas: 
- We need a hook on END_ARRAY token/event. How about adding support for array specific _function_ for _array_ _type_ fields. And a flag to indicate if the function should be invoked for nested arrays.
eg. 
```
"events": {
        "type": "array",
        "function": "processStuffArray",
        "nested": 2 // either a number which indicates nested levels or simply true/false and setting a max nested levels internally
      }
```
- Another way to handle this, is to define an anonymous array name for handling two or more nested level arrays.

**Comment by mfatihercik** [comment]
what about this idea:
```yaml
result:
   type: object
   fields:
      columns:
         type: array
      events:
         type: array
         items:
             type: array
```
