### ISSUE TITLE
The conversion seems a little problematic when the root node is an array

### ISSUE THREAD

**Issue by stoneNyKing** [mfatihercik/dsm#16]
version:1.0.4

source json:
[
  {
    "address": {
      "se": {
        "db": "f"
      },
      "addressName": "2dsf3",
      "addressPwd": "323"
    }
  }
]

mapping json:
{
  "result" : {
    "path" : "/",
    "type" : "array",
    "fields" : {
      "address": {
        "type": "object",
        "path": "/address",
        "fields": {
          "addressName" :{
            "path": "/address/addressName",
            "dataType": "string"
          },
          "addressPwd": {
            "path": "/address/addressPwd",
            "dataType": "string"
          }
        }
      }
    }
  }
}
result:
[{address={addressName=2dsf3, addressPwd=323}}, {address={addressName=2dsf3, addressPwd=323}}]

**Comment by chipcats** [comment]
I meet this problem too,could u share how did u deal with it?

**Comment by chipcats** [comment]
> 

well, I just note that author had fixed it

**Comment by mfatihercik** [comment]
I published a new version. 1.0.5. It should be available on nexus. I was a little busy sorry folks.
