### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by wendersonferreira** [mfatihercik/dsm#20]
Firstly, congratulations on the project, it's quite creative. For the filter, let's suppose I have a source.json
//source.json
[
  {
    "provider": "VODAFONE"
  },
  {
    "provider": "VERIZON"
  },
  {
    "provider": "TEXAS"
  }
]

//config
version: 0.1.0
result:
  type: array
  path: /
  filter: $self.data.provider == 'TEXAS' || $self.data.provider == 'VODAFONE'
  #filter: $self.data.provider == 'TEXAS' or $self.data.provider == 'VODAFONE' i tried it too
  fields:
    provider: string

I would like to filter by texas and vodafone, but it is returning only records for the first branch, maybe i lost something.

**Comment by mfatihercik** [comment]
It is working in the below code. Please have a look. The expression starts with $, but it doesn't mean that you should use self without $ sing.
wrong expression: $self.data.provider == 'TEXAS' || **$** self.data.provider == 'VODAFONE'

correct expression:
**$self.data.provider == 'TEXAS' || self.data.provider == 'VODAFONE'**


```

public class Main {
    public static void main(String[] args) {
        var input = """
                [
                                   {
                                   "provider": "VODAFONE"
                                   },
                                   {
                                   "provider": "VERIZON"
                                   },
                                   {
                                   "provider": "TEXAS"
                                   }
                                   ]
                                
                """;

        var mapping = """
                result:
                  path: /
                  type: array
                  filter: $self.data.provider == 'TEXAS' or self.data.provider == 'VODAFONE'
                  fields:
                    provider:
                """;


        var dsm = new DSMBuilder(mapping).setType(DSMBuilder.TYPE.JSON).create();


        var result = dsm.toObject(input);

        System.out.println(result);
    }
}
```

Result: 

`[{provider=VODAFONE}, {provider=TEXAS}]`
