### ISSUE TITLE
help to check XML node

### ISSUE THREAD

**Issue by marcosbis** [mfatihercik/dsm#21]
great stuff!.

how can I map the following when the XML node define the value:

XML Source:
`<GigabitEthernet>
    <name>1/0/5</name>
    <speed>
        <auto/>
    </speed>
</GigabitEthernet>`

or 

`<GigabitEthernet>
  <name>1/0/6</name>
  <speed>
      <1g/>
  </speed>
</GigabitEthernet>`

Expected result:
    ` {
        "name":"1/0/5",
        "speed":"AUTO"
       }`
or
       `{
        "name":"1/0/6",
        "speed":"1000"
       }`

**Comment by mfatihercik** [comment]
Hi @marcosbis ,

First of all thank you!,

The XML you provided is [not valid. ](https://www.w3schools.com/xml/xml_elements.asp)
XML tag name cannot start with number like **<1g/>**
<img width="722" alt="image" src="https://github.com/mfatihercik/dsm/assets/4737611/f27eba19-eb84-49a2-a73e-a194d804ba73">

You can use following configuration to set value by tag names. The idea here is if the parser sees a tag, it will set a default value for that tag.

```java

import com.github.mfatihercik.dsb.DSMBuilder;

public class Main {
    public static void main(String[] args) {
        var input = """
                <GigabitEthernet>
                    <name>1/0/5</name>
                    <speed>
                        <g2/>
                    </speed>
                </GigabitEthernet>
                                
                """;

        var mapping = """
                result:
                  path: /GigabitEthernet
                  type: object
                  fields:
                    name:
                    speed:
                      - parentPath: speed/auto
                        default: auto
                      - parentPath: speed/g
                        default: 1000
                      - parentPath: speed/g2
                        default: 2000
                                               
                """;


        var dsm = new DSMBuilder(mapping).setType(DSMBuilder.TYPE.XML).create();


        var result = dsm.toObject(input);

        System.out.println(result);
    }
}
```
