### ISSUE TITLE
dynamic filter - clarification - Urgent

### ISSUE THREAD

**Issue by mydata** [mfatihercik/dsm#8]
with this library, is it possible to have filter expression to match inputs?
for eg: self.data.salary>10000, is it possible to accept the value to be compared (instead of hard coded value 10000) from input? like from java.

I have a requirement as follows
    I have an array of objects as follows 
   {
  "operations" : [
    {
      "name" : "operationname1",
      "version" : "version",
      "operationtype" : "single",
      "transformationclass" :"fullpackage class"
    },
{
      "name" : "operationname2",
      "version" : "version",
      "operationtype" : "single",
      "transformationclass" :"fullpackage class"
    }
  ]
}

a) I get operation name and version from input, so i need to load only operation type and transformationClass only for the provided inputs. Is that even possible with DSM library?

b) If thats not possible, I can try loading all the elements always and do normal java Collection Streams operation to filter - In this case what benefit will i get , as it is same as loading using ObjectMapper ( jackson Library).

c) is DSM supported for concurrent operations?

**Comment by mfatihercik** [comment]
**Answer for A and B:**

DSM allows passing parameter from java.

 let's say you have following mapping definitions for your data. You can filter operation array by using the filter field.  I check equality of **version** and **name** field with **version** and **operationName** field in **params**.

```yaml
result:
  path: operations
  type: array
  filter: self.data.version==params.version and self.data.name=params.operationName
  fields:
    name:
    version: long
    operationtype:
    transformationclass:
```

Here is how to pass parameters from java :

 ```java
String operationName = "operationname1";
        String version = "version";
        
        DSMBuilder builder = new DSMBuilder(Test.class.getClassLoader().getResourceAsStream("test.yaml"));
        builder.getParams().put("version", version);
        builder.getParams().put("operationName", operationName);
       
        DSM dsm = builder.create();
        Object object = dsm.toObject(Test.class.getClassLoader().getResourceAsStream("test.json"));
        System.out.println(object);
```

**Answer For C**

Can you please give more detail?

**Comment by mydata** [comment]
Thank you for the quick response.

Normally, it is preferred to load the json only once and refresh the load on given intervals to meet the performance. So any operations on JSOn will be done on the loaded JSON. how does this work in DSM case. if we use the above code, do we need to do the load every time , as the inputs can vary per request, as this is coming from a rest api input params.

Regarding C) is it thread safe?

we are using a Spring boot based Rest api, where this operation need to be performed for each input combination of name and version.

Also how can we parse enum fields from json using DSM? is there any example i can refer?

**Comment by mfatihercik** [comment]
DSM only reads data that match with mapping definitions. So it won't load all data into memory.
in your case you will only get data match with your conditions. 
İf you want to load json data into memory and then filter it according to your condition you can use DSM to load all **operation** into cache and do normal java Collection Streams operation to filter it.
Then refresh it on given interval. 

DSM alwasy read data from begining and read as stream. So it will read data on every request in your case.


if you create DSMBuilder object and DSM object for every request it will work for multi thread. But curently you can't share DSMBuilder and DSM object betwen threads. they are not thread safe. But we think to make it thread safe.

İf your JSON data is big then you can't load all into memory. it is not efficient read from beginning on every request  You can solve your problem as follows. Create look up cache which cache key is version and operation id. if request hit the cache get it from cache otherwise find it in JSON data with DSM. invalidate cache in specified interval.

**Comment by mfatihercik** [comment]
For Enum parsing:

DSM uses Jackson to convert data to object. Thus Jackson already supports ENUM deserialisation.
But field value and ENUM name must be the same to deserialize a field to ENUM. 

İf field value and ENUM name are not matches you can use **normalize** field or use **transformationCode** field to make it exactly same.

Here is an example:

You have the following JSON:
```
{  
   "colors":[  
      {  "color":"red" },
      {  "color":"Wine Red" },
      {  "color":"blood"    },
      {  "color":"blue"      },
      {  "color":"navy"      },
      {  "color":"Green"      }
   ]
}
```

colours in above JSON are a different shade of red and blue. But you have only three enums RED and BLUE,OTHER

```
public class Colors {
    public  enum COLOR{
        RED,BLUE,OTHER
    };
    
    private COLOR color;

    public COLOR getColor() {
        return color;
    }

    public void setColor(COLOR color) {
        this.color = color;
    }
}
```

To convert these colours to ENUM you have to make the transformation.
Here is the mapping file:

```
transformations:
   COLOR:
     map:
       red: RED
       Wine Red: RED
       blood: RED
       blue: BLUE
       navy: BLUE
       DEFAULT: OTHER
result:
  path: colors
  type: array  
  fields:
    color:
      transformationCode: COLOR 
```

**Console output:**

`[Colors [color=RED], Colors [color=RED], Colors [color=RED], Colors [color=BLUE], Colors [color=BLUE], Colors [color=OTHER]].`

**Another solution is creating a custom data type converter and register it.**

```
DSMBuilder builder = new DSMBuilder(Test.class.getClassLoader().getResourceAsStream("test.yaml"));
        builder.registerTypeConverter("COLOR_TYPE", new TypeConverter() {
            
            @Override
            public Object convert(String value, Map<String, Object> params) {
                return  Colors.COLOR.valueOf("RED");  // alwasy return red
            }
        });
```

Mapping file:

```
result:
  path: colors
  type: array  
  fields:
    color: COLOR_TYPE   # use custom COLOR_TYPE converter
```

**You can choose which solution is suited for you.**
